[package]
name = "sample-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_dynamo = { version = "=4.2.0", features = ["aws-sdk-dynamodb+0_25"] }
aws-config = { version = "=0.55.0" }
aws-sdk-dynamodb = { version = "=0.25.2" }
