[package]
name = "sample-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_dynamo = { version = "=4.2.5", features = ["aws-sdk-dynamodb+0_30"] }
aws-config = { version = "=0.56.1" }
aws-sdk-dynamodb = { version = "=0.30.0" }
